{% set name = "makim" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/makim-{{ version }}.tar.gz
  sha256: d7db0a978aa634d40896043057df11ea908d982080365e409b173c3e35116369

build:
  entry_points:
    - makim = makim.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - poetry >=1.5.1
    - pip
  run:
    - __unix
    - python >=3.8.1,<4.0.0
    - sh >=2.0.0
    - pyyaml >=5.0
    - jinja2 >=2.0
    - xonsh >=0.14.0
    - python-dotenv >=0.21.1
    - colorama >=0.4.6

test:
  source_files:
    - .makim.yaml
  imports:
    - makim
  commands:
    - pip check
    - makim --help
  requires:
    - pip

about:
  home: https://github.com/osl-incubator/makim
  summary: Simplify the usage of containers
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felipepaes
    - xmnlab
